[package]
name = "smt-proof"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparse-merkle-tree = "0.5.3"
rand = "0.7"
blake2b-rs = "0.2.0"